// generated by tools/build-film.sh — do not edit
window.AXIS_FILM = {
  frames: 916, w: 1920, h: 1080, fps: 24, intro: 139,
  bright: [[57, 68], [629, 645]],
  src: i => 'film/frames/' + String(i + 1).padStart(4, '0') + '.webp',
  doors: { caesar: 'film/frames/door-caesar.webp', medici: 'film/frames/door-medici.webp', oppenheimer: 'film/frames/door-oppenheimer.webp', musk: 'film/frames/door-musk.webp' },
  eras: [
    { key: 'caesar', name: 'Julius Caesar', start: 139 },
    { key: 'medici', name: 'Lorenzo de’ Medici', start: 326 },
    { key: 'oppenheimer', name: 'J. Robert Oppenheimer', start: 465 },
    { key: 'musk', name: 'Elon Musk', start: 628 },
    { key: 'frontier', name: '????', start: 771 },
  ]
};
