#!/usr/bin/env bash
# Turns the Higgsfield clips in film/clips/ into one scroll-scrubbable
# WebP frame sequence (film/frames/) plus film/manifest.js for index.html.
#
#   tools/build-film.sh            # rebuild after replacing any clip
#
# Clips: optional film/clips/00-*.mp4 (the camera flying through the hero portal, played before
# the first scene), then film/clips/01..05-*.mp4 in scene order. Audio is ignored.
set -euo pipefail
cd "$(dirname "$0")/.."

W=${FILM_W:-1920}         # web frame width: full 1080p
Q=${FILM_Q:-80}           # WebP quality 0–100 (~half the bytes of a JPEG that looks the same)
ENC=(-c:v libwebp -quality "$Q" -compression_level 4)
XF=${FILM_XF:-6}          # frames of cross-dissolve at each seam (safety net)

KEYS=(caesar medici oppenheimer musk frontier)
NAMES=("Julius Caesar" "Lorenzo de’ Medici" "J. Robert Oppenheimer" "Elon Musk" "????")
LAST=$(( ${#KEYS[@]} - 1 ))

rm -rf film/frames film/.tmp && mkdir -p film/frames film/.tmp

clips=()
pre=$(ls film/clips/00-*.mp4 2>/dev/null | head -1 || true)
[[ -n "$pre" ]] && clips+=("$pre")
OFF=${#clips[@]}                                   # 1 when there is a portal clip before the eras
for ((i=1; i<=LAST+1; i++)); do
  f=$(ls film/clips/0${i}-*.mp4 2>/dev/null | head -1 || true)
  [[ -n "$f" ]] || { echo "missing film/clips/0${i}-*.mp4" >&2; exit 1; }
  clips+=("$f")
done
NC=${#clips[@]}

# 1. explode each clip
for ((i=0; i<NC; i++)); do
  mkdir -p film/.tmp/$i
  ffmpeg -v error -i "${clips[$i]}" -an -vf "fps=24,scale=${W}:-2:flags=lanczos" \
    "${ENC[@]}" film/.tmp/$i/%04d.webp
done

# 2. stitch: overlap XF frames at each seam with a linear dissolve so a
#    slightly-off chained start frame never reads as a cut
n=0; starts=(); counts=()
emit() { n=$((n+1)); cp "$1" "$(printf 'film/frames/%04d.webp' $n)"; }
for ((i=0; i<NC; i++)); do
  frames=(film/.tmp/$i/*.webp); total=${#frames[@]}
  first=0
  if (( i > 0 )); then
    # replace previous clip's last XF frames with a blend into this clip's first XF
    n=$((n-XF))
    for ((k=0; k<XF; k++)); do
      a=$(printf 'film/.tmp/%d/%04d.webp' $((i-1)) $((prev_total-XF+k+1)))
      b="${frames[$k]}"
      t=$(awk "BEGIN{print ($k+1)/($XF+1)}")
      n=$((n+1))
      ffmpeg -v error -y -i "$a" -i "$b" -filter_complex "blend=all_expr='A*(1-$t)+B*$t'" \
        "${ENC[@]}" "$(printf 'film/frames/%04d.webp' $n)"
    done
    first=$XF
  fi
  starts+=($((n - (i>0 ? XF : 0))))
  for ((k=first; k<total; k++)); do emit "${frames[$k]}"; done
  counts+=($total)
  prev_total=$total
done

# 3. door posters for the hall (first frame of Rome, a representative mid-frame of the rest;
#    the Next Frontier door keeps its painted glow)
doors=""
for ((i=0; i<LAST; i++)); do
  frames=(film/.tmp/$((i+OFF))/*.webp)
  pick=$(( i == 0 ? 0 : ${#frames[@]} * 55 / 100 ))
  cp "${frames[$pick]}" film/frames/door-${KEYS[$i]}.webp
  doors+="${KEYS[$i]}: 'film/frames/door-${KEYS[$i]}.webp', "
done

# 4. bright stretches (mean luma over ~200/255) so the page can drop its dark text backings over white frames
bright=$(ffmpeg -v error -framerate 24 -i film/frames/%04d.webp -vf "scale=64:-2,signalstats,metadata=print:key=lavfi.signalstats.YAVG:file=-" -f null - \
  | awk -F= '/YAVG/ { y[n++] = $2 } END {
      s = -1; out = ""
      for (i = 0; i <= n; i++) {
        hi = (i < n && y[i] > 200)
        if (hi && s < 0) s = i
        if (!hi && s >= 0) { if (i - s >= 4) out = out (out ? ", " : "") "[" s ", " i - 1 "]"; s = -1 }
      }
      print out }')

# 5. manifest
{
  echo "// generated by tools/build-film.sh — do not edit"
  echo "window.AXIS_FILM = {"
  echo "  frames: $n, w: $W, h: $((W*9/16)), fps: 24, intro: ${starts[$OFF]},"
  echo "  bright: [${bright}],"
  echo "  src: i => 'film/frames/' + String(i + 1).padStart(4, '0') + '.webp',"
  echo "  doors: { ${doors%, } },"
  echo "  eras: ["
  for ((i=0; i<=LAST; i++)); do echo "    { key: '${KEYS[$i]}', name: '${NAMES[$i]}', start: ${starts[$((i+OFF))]} },"; done
  echo "  ]"
  echo "};"
} > film/manifest.js

rm -rf film/.tmp
du -sh film/frames | awk -v n=$n '{print n " frames, " $1}'
